import type { Reactive } from 'vue'
import {
  type AiProviderCatalogItem,
  type AiProviderConfig,
  type ProviderProtocolDriver,
} from '@garlic-claw/shared'
import {
  findAiProviderCatalogItem,
  protocolDriverOptions,
} from './provider-catalog'
export {
  getProviderDriverHint,
  protocolDriverOptions,
} from './provider-catalog'

/**
 * provider 编辑表单状态。
 */
export interface ProviderFormState {
  id: string
  name: string
  driver: ProviderProtocolDriver
  apiKey: string
  baseUrl: string
  defaultModel: string
  modelsText: string
}

/**
 * 创建 provider 编辑表单的默认状态。
 * @returns 可直接交给 `reactive()` 的初始对象
 */
export function createProviderFormState(): ProviderFormState {
  return {
    id: 'openai',
    name: 'OpenAI',
    driver: 'openai',
    apiKey: '',
    baseUrl: '',
    defaultModel: '',
    modelsText: '',
  }
}

/**
 * 根据当前弹窗上下文重置表单内容。
 * @param form 表单状态
 * @param initialConfig 当前正在编辑的 provider；为空表示新建
 * @param catalog provider 目录
 */
export function syncProviderFormState(
  form: Reactive<ProviderFormState>,
  initialConfig: AiProviderConfig | null,
  catalog: AiProviderCatalogItem[],
): void {
  if (initialConfig) {
    form.id = initialConfig.id
    form.name = initialConfig.name
    form.driver = initialConfig.driver
    form.apiKey = initialConfig.apiKey ?? ''
    form.baseUrl = initialConfig.baseUrl ?? ''
    form.defaultModel = initialConfig.defaultModel ?? ''
    form.modelsText = initialConfig.models.join('\n')
    return
  }

  const firstCatalogItem = catalog[0]
  form.id = firstCatalogItem?.id ?? 'openai'
  form.name = firstCatalogItem?.name ?? 'OpenAI'
  form.driver = (firstCatalogItem?.id ?? 'openai') as ProviderProtocolDriver
  form.apiKey = ''
  form.baseUrl = firstCatalogItem?.defaultBaseUrl ?? ''
  form.defaultModel = firstCatalogItem?.defaultModel ?? ''
  form.modelsText = firstCatalogItem?.defaultModel ?? ''
}

/**
 * 根据当前驱动补齐默认值。
 * @param form 表单状态
 * @param catalog provider 目录
 * @param initialConfig 当前正在编辑的 provider
 */
export function applyProviderDriverDefaults(
  form: Reactive<ProviderFormState>,
  catalog: AiProviderCatalogItem[],
  initialConfig: AiProviderConfig | null,
): void {
  const autogeneratedNames = new Set([
    ...catalog.map((item) => item.name),
    ...protocolDriverOptions.map((item) => item.name),
  ])
  const autogeneratedBaseUrls = new Set([
    ...catalog.map((item) => item.defaultBaseUrl),
  ])
  const autogeneratedModels = new Set(catalog.map((item) => item.defaultModel))
  const autogeneratedIds = new Set(protocolDriverOptions.map((item) => item.id))
  const initialModelsText = initialConfig?.models.join('\n') ?? ''
  const catalogProvider = findAiProviderCatalogItem(catalog, form.driver)
  const protocolOption = protocolDriverOptions.find(
    (item) => item.id === form.driver,
  )

  const shouldReplaceName =
    !form.name ||
    form.name === initialConfig?.name ||
    autogeneratedNames.has(form.name)
  const shouldReplaceBaseUrl =
    !form.baseUrl ||
    form.baseUrl === initialConfig?.baseUrl ||
    autogeneratedBaseUrls.has(form.baseUrl)
  const shouldReplaceDefaultModel =
    !form.defaultModel ||
    form.defaultModel === initialConfig?.defaultModel ||
    autogeneratedModels.has(form.defaultModel)
  const shouldReplaceModelsText =
    !form.modelsText ||
    form.modelsText === initialModelsText ||
    autogeneratedModels.has(form.modelsText.trim())

  if (!initialConfig && (!form.id || autogeneratedIds.has(form.id as ProviderProtocolDriver))) {
    form.id = form.driver.trim() || 'openai'
  }

  if (catalogProvider && form.id.trim() === form.driver) {
    if (shouldReplaceName) {
      form.name = catalogProvider.name
    }
    if (shouldReplaceBaseUrl) {
      form.baseUrl = catalogProvider.defaultBaseUrl
    }
    if (shouldReplaceDefaultModel) {
      form.defaultModel = catalogProvider.defaultModel
    }
    if (shouldReplaceModelsText) {
      form.modelsText = catalogProvider.defaultModel
    }
    return
  }

  if (shouldReplaceName) {
    form.name = protocolOption?.name ?? form.driver
  }

  if (shouldReplaceBaseUrl) {
    form.baseUrl = catalogProvider?.defaultBaseUrl ?? ''
  }

  if (shouldReplaceDefaultModel) {
    form.defaultModel = ''
  }

  if (shouldReplaceModelsText) {
    form.modelsText = ''
  }
}

/**
 * 把表单状态转换成后端接口所需的 provider 配置。
 * @param form 当前表单状态
 * @returns 已整理好的 provider 配置
 */
export function buildProviderConfigPayload(
  form: Reactive<ProviderFormState>,
): AiProviderConfig {
  return {
    id: form.id.trim(),
    name: form.name.trim(),
    driver: form.driver,
    apiKey: form.apiKey.trim() || undefined,
    baseUrl: form.baseUrl.trim() || undefined,
    defaultModel: form.defaultModel.trim() || undefined,
    models: form.modelsText
      .split(/[\n,]/)
      .map((item) => item.trim())
      .filter(Boolean),
  }
}
