import type { PluginHostMethod, PluginPermission } from '@garlic-claw/shared';

export const CONNECTION_SCOPED_PLUGIN_HOST_METHODS = [
  'config.get',
  'cron.delete',
  'cron.list',
  'cron.register',
  'kb.get',
  'kb.list',
  'kb.search',
  'log.list',
  'log.write',
  'persona.current.get',
  'persona.get',
  'persona.list',
  'plugin.self.get',
  'provider.current.get',
  'provider.get',
  'provider.list',
  'provider.model.get',
  'runtime.command.execute',
  'runtime.fs.edit',
  'runtime.fs.glob',
  'runtime.fs.grep',
  'runtime.fs.read',
  'runtime.fs.write',
  'state.delete',
  'state.get',
  'state.list',
  'state.set',
  'storage.delete',
  'storage.get',
  'storage.list',
  'storage.set',
] as const satisfies PluginHostMethod[];

export const PLUGIN_HOST_METHOD_PERMISSION_MAP = {
  'automation.create': 'automation:write',
  'automation.event.emit': 'automation:write',
  'automation.list': 'automation:read',
  'automation.run': 'automation:write',
  'automation.toggle': 'automation:write',
  'config.get': 'config:read',
  'cron.delete': 'cron:write',
  'cron.list': 'cron:read',
  'cron.register': 'cron:write',
  'conversation.get': 'conversation:read',
  'conversation.history.get': 'conversation:read',
  'conversation.history.preview': 'conversation:read',
  'conversation.history.replace': 'conversation:write',
  'conversation.session.finish': 'conversation:write',
  'conversation.session.get': 'conversation:write',
  'conversation.session.keep': 'conversation:write',
  'conversation.session.start': 'conversation:write',
  'conversation.messages.list': 'conversation:read',
  'conversation.title.set': 'conversation:write',
  'kb.get': 'kb:read',
  'kb.list': 'kb:read',
  'kb.search': 'kb:read',
  'llm.generate': 'llm:generate',
  'llm.generate-text': 'llm:generate',
  'log.list': 'log:read',
  'log.write': 'log:write',
  'message.send': 'conversation:write',
  'message.target.current.get': 'conversation:read',
  'memory.search': 'memory:read',
  'memory.save': 'memory:write',
  'persona.activate': 'persona:write',
  'persona.current.get': 'persona:read',
  'persona.get': 'persona:read',
  'persona.list': 'persona:read',
  'plugin.self.get': null,
  'provider.current.get': 'provider:read',
  'provider.get': 'provider:read',
  'provider.list': 'provider:read',
  'provider.model.get': 'provider:read',
  'runtime.command.execute': 'runtime:command',
  'runtime.fs.edit': 'runtime:write',
  'runtime.fs.glob': 'runtime:read',
  'runtime.fs.grep': 'runtime:read',
  'runtime.fs.read': 'runtime:read',
  'runtime.fs.write': 'runtime:write',
  'storage.delete': 'storage:write',
  'storage.get': 'storage:read',
  'storage.list': 'storage:read',
  'storage.set': 'storage:write',
  'subagent.close': 'subagent:run',
  'subagent.get': 'subagent:run',
  'subagent.interrupt': 'subagent:run',
  'subagent.list': 'subagent:run',
  'subagent.send-input': 'subagent:run',
  'subagent.spawn': 'subagent:run',
  'subagent.wait': 'subagent:run',
  'state.delete': 'state:write',
  'state.get': 'state:read',
  'state.list': 'state:read',
  'state.set': 'state:write',
  'user.get': 'user:read',
} as const satisfies Record<PluginHostMethod, PluginPermission | null>;
